---
title: "GeoR_CH3_Katchen"
author: "Jordan Katchen"
date: "2023-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Library

```{r}
library(sf)      # vector data package introduced in Chapter 2
library(terra)   # raster data package introduced in Chapter 2
library(dplyr)   # tidyverse package for data frame manipulation
library(spData)  # spatial data package introduced in Chapter 2
library(tidyr)
```

## Exersices

### 3.2

```{r}
class(world) # it's an sf object and a (tidy) data frame
dim(world)   # it is a 2 dimensional object, with 177 rows and 11 columns

world_df = st_drop_geometry(world)
class(world_df)
ncol(world_df)
```

```{r}
world[1:6, ]    # subset rows by position
world[, 1:3]    # subset columns by position
world[1:6, 1:3] # subset rows and columns by position
world[, c("name_long", "pop")] # columns by name
world[, c(T, T, F, F, F, F, F, T, T, F, F)] # by logical indices
world[, 888] # an index representing a non-existent column
```

```{r}
i_small = world$area_km2 < 10000
summary(i_small)
small_countries = world[i_small, ]
```

```{r}
small_countries = subset(world, area_km2 < 10000)
```

```{r}
world1 = dplyr::select(world, name_long, pop)
names(world1)
# all columns between name_long and pop (inclusive)
world2 = dplyr::select(world, name_long:pop)
# all columns except subregion and area_km2 (inclusive)
world3 = dplyr::select(world, -subregion, -area_km2)
world4 = dplyr::select(world, name_long, population = pop)
```

```{r}
world5 = world[, c("name_long", "pop")] # subset columns by name
names(world5)[names(world5) == "pop"] = "population" # rename column manually
```

```{r}
pull(world, pop)
world$pop
world[["pop"]]
```

```{r}
slice(world, 1:6)
world7 = filter(world ,area_km2 < 10000) # countries with a small area
world7 = filter(world, lifeExp > 82)      # with high life expectancy
```

```{r}
world7 = world |>
  filter(continent == "Asia") |>
  dplyr::select(name_long, continent) |>
  slice(1:5)
```

```{r}
world8 = slice(
  dplyr::select(
    filter(world, continent == "Asia"),
    name_long, continent),
  1:5)
```

```{r}
world9_filtered = filter(world, continent == "Asia")
world9_selected = dplyr::select(world9_filtered, continent)
world9 = slice(world9_selected, 1:5)
```

```{r}
world_agg1 = aggregate(pop ~ continent, FUN = sum, data = world,
                       na.rm = TRUE)
class(world_agg1)
```

```{r}
world_agg2 = aggregate(world["pop"], list(world$continent), FUN = sum, 
                       na.rm = TRUE)
class(world_agg2)
nrow(world_agg2)
```

```{r}
world_agg3 = world |>
  group_by(continent) |>
  summarize(pop = sum(pop, na.rm = TRUE))
```

```{r}
world_agg4  = world |> 
  group_by(continent) |> 
  summarize(pop = sum(pop, na.rm = TRUE), `area_sqkm` = sum(area_km2), n = n())
```

```{r}
world_agg5 = world |> 
  st_drop_geometry() |>                      # drop the geometry for speed
  dplyr::select(pop, continent, area_km2) |> # subset the columns of interest  
  group_by(continent) |>                     # group by continent and summarize:
  summarize(Pop = sum(pop, na.rm = TRUE), Area = sum(area_km2), N = n()) |>
  mutate(Density = round(Pop / Area)) |>     # calculate population density
  slice_max(Pop, n = 3) |>                   # keep only the top 3
  arrange(desc(N))                           # arrange in order of n. countries
```

```{r}
world_coffee = left_join(world, coffee_data)
class(world_coffee)
```

```{r}
names(world_coffee)
plot(world_coffee["coffee_production_2017"])
```

```{r}
coffee_renamed = rename(coffee_data, nm = name_long)
world_coffee2 = left_join(world, coffee_renamed, by = c(name_long = "nm"))
```

```{r}
world_coffee_inner = inner_join(world, coffee_data)
nrow(world_coffee_inner)
```

```{r}
setdiff(coffee_data$name_long, world$name_long)
```

```{r}
(drc = stringr::str_subset(world$name_long, "Dem*.+Congo"))
```

```{r}
coffee_data$name_long[grepl("Congo,", coffee_data$name_long)] = drc
world_coffee_match = inner_join(world, coffee_data)
nrow(world_coffee_match)
```

```{r}
coffee_world = left_join(coffee_data, world)
class(coffee_world)
```

```{r}
world_new = world # do not overwrite our original data
world_new$pop_dens = world_new$pop / world_new$area_km2
```

```{r}
world |> 
  mutate(pop_dens = pop / area_km2)
```

```{r}
world |> 
  transmute(pop_dens = pop / area_km2)
```

```{r}
world_unite = world |>
  tidyr::unite("con_reg", continent:region_un, sep = ":", remove = TRUE)
```

```{r}
world_separate = world_unite |>
  tidyr::separate(con_reg, c("continent", "region_un"), sep = ":")
```

```{r}
world |> 
  rename(name = name_long)
```

```{r}
new_names = c("i", "n", "c", "r", "s", "t", "a", "p", "l", "gP", "geom")
world_new_names = world |>
  setNames(new_names)
```

```{r}
world_data = world |> st_drop_geometry()
class(world_data)
```

### 3.3

```{r}
elev = rast(nrows = 6, ncols = 6,
            xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
            vals = 1:36)
```

```{r}
grain_order = c("clay", "silt", "sand")
grain_char = sample(grain_order, 36, replace = TRUE)
grain_fact = factor(grain_char, levels = grain_order)
grain = rast(nrows = 6, ncols = 6, 
             xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
             vals = grain_fact)
```

```{r}
levels(grain) = data.frame(value = c(0, 1, 2), wetness = c("wet", "moist", "dry"))
levels(grain)
```

```{r}
elev[1, 1]
elev[1]
```

```{r}
elev[1, 1] = 0
elev[]
```

```{r}
elev[1, c(1, 2)] = 0
```

```{r}
two_layers = c(grain, elev) 
two_layers[1] = cbind(c(3), c(4))
two_layers[]
```

```{r}
global(elev, sd)
```

```{r}
hist(elev)
```

### Exerises 

```{r}
library(sf)
library(dplyr)
library(terra)
library(spData)
data(us_states)
data(us_states_df)
```

```{r}
us_states_name = select(us_states, NAME)
```

```{r}
us_states_2nd = us_states[, c("total_pop_10", "total_pop_15")]
us_states_3nd = us_states[, c(5, 6)]
```