---
title: "GeoR_CH2_Katchen"
author: "Jordan Katchen"
date: "2023-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library

```{r}
library(sf)          # classes and functions for vector data
library(terra)      # classes and functions for raster data
library(spData)        # load geographic data
library(spDataLarge)   # load larger geographic data
library(tidyverse)
```

## TEXT

### 2.2

```{r}
plot(world)
```

```{r}
world_mini = world[1:2, 1:3]
world_mini
```

```{r}
world_dfr = st_read(system.file("shapes/world.shp", package = "spData"))
world_tbl = read_sf(system.file("shapes/world.shp", package = "spData"))
class(world_dfr)
class(world_tbl)
```

```{r}
library(sp)
world_sp = as(world, "Spatial") # from an sf object to sp
# sp functions ...
world_sf = st_as_sf(world_sp)           # from sp to sf
```

```{r}
plot(world[3:6])
plot(world["pop"])
```

```{r}
world_asia = world[world$continent == "Asia", ]
asia = st_union(world_asia)
plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "red")
```

```{r}
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE)
plot(st_geometry(world_cents), add = TRUE, cex = cex)
```

```{r}
india = world[world$name_long == "India", ]
plot(st_geometry(india), expandBB = c(1, 1, 0.1, 1), col = "gray", lwd = 3)
plot(st_geometry(world_asia), add = TRUE)
```

```{r}
lnd_point = st_point(c(0.1, 51.5))                 # sfg object
lnd_geom = st_sfc(lnd_point, crs = "EPSG:4326")    # sfc object
lnd_attrib = data.frame(                           # data.frame object
  name = "London",
  temperature = 25,
  date = as.Date("2017-06-21")
  )
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom)    # sf object
```

```{r}
lnd_sf
class(lnd_sf)
```

```{r}
st_point(c(5, 2))                 # XY point
#> POINT (5 2)
st_point(c(5, 2, 3))              # XYZ point
#> POINT Z (5 2 3)
st_point(c(5, 2, 1), dim = "XYM") # XYM point
#> POINT M (5 2 1)
st_point(c(5, 2, 3, 1))           # XYZM point
#> POINT ZM (5 2 3 1)
```

```{r}
# the rbind function simplifies the creation of matrices
## MULTIPOINT
multipoint_matrix = rbind(c(5, 2), c(1, 3), c(3, 4), c(3, 2))
st_multipoint(multipoint_matrix)
#> MULTIPOINT ((5 2), (1 3), (3 4), (3 2))
## LINESTRING
linestring_matrix = rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2))
st_linestring(linestring_matrix)
#> LINESTRING (1 5, 4 4, 4 1, 2 2, 3 2)
```

```{r}
## POLYGON
polygon_list = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
st_polygon(polygon_list)
#> POLYGON ((1 5, 2 2, 4 1, 4 4, 1 5))
```

```{r}
## POLYGON with a hole
polygon_border = rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))
polygon_hole = rbind(c(2, 4), c(3, 4), c(3, 3), c(2, 3), c(2, 4))
polygon_with_hole_list = list(polygon_border, polygon_hole)
st_polygon(polygon_with_hole_list)
#> POLYGON ((1 5, 2 2, 4 1, 4 4, 1 5), (2 4, 3 4, 3 3, 2 3, 2 4))
```

```{r}
## MULTILINESTRING
multilinestring_list = list(rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
                            rbind(c(1, 2), c(2, 4)))
st_multilinestring((multilinestring_list))
#> MULTILINESTRING ((1 5, 4 4, 4 1, 2 2, 3 2), (1 2, 2 4)

## MULTIPOLYGON
multipolygon_list = list(list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))),
                         list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2))))
st_multipolygon(multipolygon_list)
#> MULTIPOLYGON (((1 5, 2 2, 4 1, 4 4, 1 5)), ((0 2, 1 2, 1 3, 0 3, 0 2)))

## GEOMETRYCOLLECTION
geometrycollection_list = list(st_multipoint(multipoint_matrix),
                              st_linestring(linestring_matrix))
st_geometrycollection(geometrycollection_list)
#> GEOMETRYCOLLECTION (MULTIPOINT (5 2, 1 3, 3 4, 3 2),
#>   LINESTRING (1 5, 4 4, 4 1, 2 2, 3 2))
```

```{r}
# sfc POINT
point1 = st_point(c(5, 2))
point2 = st_point(c(1, 3))
points_sfc = st_sfc(point1, point2)
points_sfc

# sfc POLYGON
polygon_list1 = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
polygon1 = st_polygon(polygon_list1)
polygon_list2 = list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2)))
polygon2 = st_polygon(polygon_list2)
polygon_sfc = st_sfc(polygon1, polygon2)
st_geometry_type(polygon_sfc)

# sfc MULTILINESTRING
multilinestring_list1 = list(rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
                            rbind(c(1, 2), c(2, 4)))
multilinestring1 = st_multilinestring((multilinestring_list1))
multilinestring_list2 = list(rbind(c(2, 9), c(7, 9), c(5, 6), c(4, 7), c(2, 7)), 
                            rbind(c(1, 7), c(3, 8)))
multilinestring2 = st_multilinestring((multilinestring_list2))
multilinestring_sfc = st_sfc(multilinestring1, multilinestring2)
st_geometry_type(multilinestring_sfc)
```

```{r}
point_multilinestring_sfc = st_sfc(point1, multilinestring1)
st_geometry_type(point_multilinestring_sfc)
```

```{r}
# Set the CRS with an identifier referring to an 'EPSG' CRS code:
points_sfc_wgs = st_sfc(point1, point2, crs = "EPSG:4326")
st_crs(points_sfc_wgs) # print CRS (only first 4 lines of output shown)
```

```{r}
sf_use_s2()
```

### 2.3

```{r}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
my_rast = rast(raster_filepath)
class(my_rast)
my_rast
```

```{r}
plot(my_rast)
```

```{r}
single_raster_file = system.file("raster/srtm.tif", package = "spDataLarge")
single_rast = rast(raster_filepath)
```

```{r}
new_raster = rast(nrows = 6, ncols = 6, 
                  xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
                  vals = 1:36)
```

```{r}
multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
multi_rast = rast(multi_raster_file)
multi_rast
```

```{r}
multi_rast3 = subset(multi_rast, 3)
multi_rast4 = subset(multi_rast, "landsat_4")
multi_rast34 = c(multi_rast3, multi_rast4)
```

### 2.6

```{r}
luxembourg = world[world$name_long == "Luxembourg", ]
st_area(luxembourg)
```

```{r}
units::set_units(st_area(luxembourg), km^2)
```

```{r}
repr = project(my_rast, "EPSG:26912")
res(repr)
```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


## EXERSICES

E1
```{r}
summary(world)
```

E2
```{r}
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE)
plot(st_geometry(world_cents), add = TRUE, cex = cex)
```

E3
```{r}
world_afaca = world[world$continent == "Africa", ]
Nigeria = world[world$name_long == "Nigeria", ]
plot(st_geometry(Nigeria), expandBB = c(2, 0.4, 0.4, 1), col = "darkseagreen3", lwd = 3)
plot(st_geometry(world_afaca), add = TRUE)
```

E4
```{r}
new_raster = rast(nrows = 10, ncols = 10, 
                  xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
                  vals = sample(0:10, size = 10 * 10, replace = TRUE))
new_raster
plot(new_raster)
```

E5
```{r}
rast_fast = rast(system.file("raster/nlcd.tif", package = "spDataLarge"))
rast_fast
plot(rast_fast)
```

Efun
```{r}
world_namerica = world[world$continent == "North America", ]
Canada = world[world$name_long == "Canada", ]
plot(st_geometry(Canada), expandBB = c(2, 0.4, 0.4, 1), col = "gray", lwd = 3)
plot(st_geometry(world_namerica), add = TRUE)
```

```{r}
world_afaca = world[world$continent == "Africa", ]
world_namerica = world[world$continent == "North America", ]
Canada = world[world$name_long == "Canada", ]
Nigeria = world[world$name_long == "Nigeria", ]
plot(st_geometry(Canada), expandBB = c(2, 0.4, 0.4, 1), col = "gray", lwd = 3)
plot(st_geometry(Nigeria), expandBB = c(2, 0.4, 0.4, 1), col = "red", lwd = 3, add = TRUE)
plot(st_geometry(world_namerica), add = TRUE)
plot(st_geometry(world_afaca), add = TRUE)
```

```{r}
world_afaca = world[world$continent == "Africa", ]
world_namerica = world[world$continent == "North America", ]
Canada = world[world$name_long == "Canada", ]
Nigeria = world[world$name_long == "Nigeria", ]
plot(st_geometry(world), col = "lightgray")
plot(st_geometry(Canada), expandBB = c(2, 0.4, 0.4, 1), col = "gray", lwd = 3, add = TRUE)
plot(st_geometry(Nigeria), expandBB = c(2, 0.4, 0.4, 1), col = "red", lwd = 3, add = TRUE)
```

```{r}
world_afaca = world[world$continent == "Africa", ]
world_namerica = world[world$continent == "North America", ]
Canada = world[world$name_long == "Canada", ]
Nigeria = world[world$name_long == "Nigeria", ]
plot(st_geometry(world), col = "lightgray")
plot(st_geometry(Canada), expandBB = c(2, 0.4, 0.4, 1), col = "red", lwd = 3, add = TRUE)
plot(st_geometry(Nigeria), expandBB = c(2, 0.4, 0.4, 1), col = "green", lwd = 3, add = TRUE)
```
